---
- name: Install Java and deploy application
  hosts: all
  become: yes
  remote_user: ubuntu

  vars:
    source_dir: files
    dest_dir: /home/ubuntu/
    files:
      - properties.py
      - start.sh
      - spring-petclinic-3.2.0-SNAPSHOT.jar

  tasks:
    - name: Copy properties.py to the server
      copy:
        src: "{{ source_dir }}/properties.py"
        dest: "{{ dest_dir }}/properties.py"

    - name: Copy start.sh to the server
      copy:
        src: "{{ source_dir }}/start.sh"
        dest: "{{ dest_dir }}/start.sh"
        mode: '0755'

    - name: Copy spring-petclinic-3.2.0-SNAPSHOT.jar to the server
      copy:
        src: "{{ source_dir }}/spring-petclinic-3.2.0-SNAPSHOT.jar"
        dest: "{{ dest_dir }}/spring-petclinic-3.2.0-SNAPSHOT.jar"

    - name: Copy application.properties to the server
      copy:
        src: "{{ source_dir }}/application.properties"
        dest: "{{ dest_dir }}/application.properties"
